#!/bin/bash
set -o errexit

# convert markdown from README.md to temp.html
[ -f README.md ] && markdown_py2 -x toc -x extra README.md > temp.html || exit 6
[ -f doc_start.html ] && rm -fv doc_start.html || exit 7

vim -E -V doc_template.html <<- END
    /^$
    :read temp.html
    :write doc_start.html
    :quit
END

[ -f temp.html ] && rm -fv temp.html || exit 8
[ -f doc_start.html ] && cp -v doc_start.html ../../README.html || exit 9

# create docs for AnkiWeb
[ -f htmlforankiweb.py ] && ./htmlforankiweb.py || exit 10
