#!/bin/bash

set -o errexit
set -o nounset

FOLDER_NAME=power_format_pack

usage() {
    echo >&2 "usage: $(basename "$0") <version number>"
}

die() {
    echo >&2 "$1"
    exit "$2"
}

check_version_format() {
    version="$1"

    if [[ ! "$version" =~ ^[0-9.]+[0-9]$ ]]; then
        die "Version string '$version' is not formatted correctly. Exiting..." 2
    fi
}

remove_backup_file() {
    if [ -z "$1" ]; then
        quit
    else
        file="$1"
        if [ -f "$file".bak ]; then
            rm "$file".bak
        fi
    fi
}

if [[ "${1:-unset}" == unset ]]; then
    usage
    exit 1
else
    check_version_format "$1"
    NEW_VERSION="$1"
fi

FILES=("$FOLDER_NAME"/const.py "$FOLDER_NAME"/docs/_version.py)

for file in "${FILES[@]}"; do
    remove_backup_file "$file"
    sed -r -i.bak 's/(.*?version.*?)"[^"]+"/\1"'"${NEW_VERSION}"'"/I' "$file"
done

# .ini files
for file in "$FOLDER_NAME"/*.ini; do
    remove_backup_file "$file"
    sed -r -i.bak -e 's/^(version=)[0-9.]+/\1'"${NEW_VERSION}"'/I'          \
                  -e 's/^(time=).*$/\1'"$(date -Iminutes)"'/I'              \
                  -e 's/^(year_last=).*$/\1'"$(date +'%Y')"'/I' "$file"
done
