#!/bin/bash

set -o errexit
set -o nounset

set -xv

FOLDER_NAME=power_format_pack

quit() {
    echo "Need an argument. Exiting..."
    exit 1
}

check_version_format() {
    if [ -z "$1" ]; then
        quit
    fi

    version="$1"

    if [[ ! "$version" =~ ^[0-9.]+[0-9]$ ]]; then
        echo "Version string '$version' is not formatted correctly. Exiting..."
        exit 1
    fi
}

if [ -z "$1" ]; then
    quit
else
    check_version_format "$1"
    NEW_VERSION="$1"
fi

remove_backup_file() {
    if [ -z "$1" ]; then
        quit
    else
        file="$1"
        if [ -f "$file".bak ]; then
            rm -v "$file".bak
        fi
    fi
}

FILES=("$FOLDER_NAME"/const.py "$FOLDER_NAME"/docs/_version.py)

for file in "${FILES[@]}"; do
    remove_backup_file "$file"
    sed -r -i.bak 's/(.*?version.*?)"[^"]+"/\1"'"${NEW_VERSION}"'"/I' "$file"
done

# .ini files
for file in "$FOLDER_NAME"/*.ini; do
    remove_backup_file "$file"
    sed -r -i.bak -e 's/^(version=)[0-9.]+/\1'"${NEW_VERSION}"'/I'          \
                  -e 's/^(time=).*$/\1'"$(date -Iminutes)"'/I'              \
                  -e 's/^(year_last=).*$/\1'"$(date +'%Y')"'/I' "$file"
done
