#!/bin/bash

set -o errexit
set -o nounset

set -xv

if [ -z "$1" ]; then
    echo "Need an argument. Exiting..."
    exit 1
else
    NEW_VERSION="$1"
fi

CURRENT_VERSION=$(sed -r 's/__version__ = "([^"]+)"/\1/' extra_buttons/docs/_version.py)
FILES=(extra_buttons/const.py extra_buttons/docs/_version.py)

for file in "${FILES[@]}"; do
    if [ -f "$file".bak ]; then
        rm -v "$file".bak
    fi
done

for file in "${FILES[@]}"; do
    sed -r -i.bak 's/(.*?version.*?)"[^"]+"/\1"'"$NEW_VERSION"'"/I' "$file"
done
