#!/bin/bash
set -o errexit

zip ~/Desktop/supplementary_buttons_anki_$(date +%s).zip \
    "Supplementary Buttons Anki.py" \
    extra_buttons/icons/* \
    extra_buttons/extra_buttons.py \
    extra_buttons/__init__.py \
    extra_buttons/const.py \
    extra_buttons/menu.py \
    extra_buttons/preferences.py \
    extra_buttons/utility.py
    extra_buttons/anki_modules/* \
    extra_buttons/docs/doc_start.html \
    extra_buttons/html2text/* \
    extra_buttons/markdown/* \
    extra_buttons/markdowner.py \
    extra_buttons/pygments/* \
    extra_buttons/python_modules/*
