#!/bin/bash

set -o errexit
set -o nounset

set -xv

check_return_value() {
    if [ $1 -ne 0 ]; then
        echo "Command did not run succesfully. Please check. Exiting..."
        exit 1
    fi
}

# run tests before creating zip
nosetests2 -x --rednose
check_return_value $?

# remove asserts from files
while read -r file; do
    sed -i.bak -r 's/assert isinstance/# assert isinstance/' "$file"
done < <(grep -l -F "assert isinstance" extra_buttons/*.py --no-messages)

# set ignore UserWarnings
sed -i.bak -r '
s/^# *warnings/warnings/
s/^# *import +warnings/import warnings/
' extra_buttons/extra_buttons.py

grep -P "^import\s+warnings$" extra_buttons/extra_buttons.py
check_return_value $?
grep -P "^warnings\.simplefilter" extra_buttons/extra_buttons.py
check_return_value $?

zip -r --exclude=*.pyc* --exclude=*__pycache__* ~/Desktop/supplementary_buttons_anki_$(date +%s).zip \
    "Supplementary Buttons Anki.py" \
    extra_buttons/__init__.py \
    extra_buttons/abbreviation.py \
    extra_buttons/blockquote.py \
    extra_buttons/const.py \
    extra_buttons/deflist.py \
    extra_buttons/extra_buttons.py \
    extra_buttons/heading.py \
    extra_buttons/hyperlink.py \
    extra_buttons/markdowner.py \
    extra_buttons/menu.py \
    extra_buttons/orderedlist.py \
    extra_buttons/preferences.py \
    extra_buttons/table.py \
    extra_buttons/utility.py \
    extra_buttons/docs/doc_start.html \
    extra_buttons/docs/github-markdown.css \
    extra_buttons/docs/__init__.py \
    extra_buttons/docs/_version.py \
    extra_buttons/anki_modules/* \
    extra_buttons/icons/* \
    extra_buttons/html2text/* \
    extra_buttons/markdown/* \
    extra_buttons/pygments/* \
    extra_buttons/python_modules/*

# reinsert asserts and warnings comments
for file in extra_buttons/*.bak; do
    mv -v "$file" "${file%.*}"
done
